server:
  port: 8443
  max-http-header-size: 8192
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: tomcat
    enabled: true
  servlet:
    context-path: /
    session:
      timeout: 30m
  compression:
      enabled: true
      mime-types: text/html,text/css,application/javascript,application/json

spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/soaic?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: hellospringboot
  http:
    encoding:
      charset: UTF-8
      force: true
  jackson:
    default-property-inclusion: non_null
  mvc:
    favicon:
      enabled: true


mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.soaic.hellospringboot.entity

# 分页插件配置
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  page-size-zero: false